before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.26.1
branches:
  only:
    - master
    - /^v\d+.\d+.\d+$/
cache: yarn
language: node_js
notifications:
  email:
    on_failure: always
    on_success: change
